---
development:
  API_HOST: http://localhost:3030 
  API_VER: api/v0.1

test:
  API_HOST: http://localhost:3000 
  API_VER: api/v0.1
  APP_URL: http://localhost:9000

production:
  API_HOST: https://thx-seafood.herokuapp.com
  API_VER: api/v0.1
  # APP_URL: 還沒deploy

